### ISSUE TITLE
Different cooperative tradeoff solutions between first and second run

### ISSUE THREAD

**Issue by gzampieri** [micom-dev/micom#30]
Hi,

I am experiencing instability with MICOM when solving some cooperative tradeoff problems in small communities (2-5 species).
In short: assuming that a problem solved on a certain community gives a flux solution S, the same problem solved again returns a flux solution S' (all arguments and constraints being equal). After the second run, the returned solution remains S'.

Below there is a two-model community example using the E. coli [iJO1366](http://bigg.ucsd.edu/models/iJO1366) model from BiGG.

System information:
OS Ubuntu 16.04
CPLEX 12.8
python 3.6.12
pandas 1.1.3
cobra 0.20.0
micom 0.21.3

```
import pandas as pd
import micom as mc

species_names = ['ecoli1', 'ecoli2']
model_paths = ['iJO1366.xml', 'iJO1366.xml']
abundances = [0.5, 0.5]
species_df = pd.DataFrame(data={'id': species_names, 'file': model_paths, 'abundance': abundances})
com = mc.Community(species_df, solver='cplex')

sol1 = com.cooperative_tradeoff(fraction = 0.5, fluxes=True, pfba=True)
sol2 = com.cooperative_tradeoff(fraction = 0.5, fluxes=True, pfba=True)
sol3 = com.cooperative_tradeoff(fraction = 0.5, fluxes=True, pfba=True)

print('first vs second:')
print((sol1.fluxes.round(6) - sol2.fluxes.round(6)).abs().max().max())
print('first vs third:')
print((sol1.fluxes.round(6) - sol3.fluxes.round(6)).abs().max().max())
```
Expected output:
```
first vs second:
0.0
first vs third:
0.0
```
Obtained output:
```
first vs second:
0.002876000000000545
first vs third:
0.002876000000000545
```
The status is optimal for all the three solutions.

While in this example the maximum flux difference is not dramatic, it tends to increase with more limiting medium uptake bounds, and it grows worringly large with communities composed by automatically-generated models. Apart from individual model instabilities, this behaviour would seem to depend also on some numerical instability in cooperative tradeoff that gets adjusted by CPLEX after the first run, seeing previous discussions https://github.com/opencobra/cobrapy/issues/924.

It would seem that S' is the solution to be trusted given that it remains stable even after the third run, and because the two identical models in the example above get equal growth rates only in S' (up to solver tolerance):
```
print(sol1.members.loc['ecoli1', 'growth_rate'].round(6) == sol1.members.loc['ecoli2', 'growth_rate'].round(6))
print(sol2.members.loc['ecoli1', 'growth_rate'].round(6) == sol2.members.loc['ecoli2', 'growth_rate'].round(6))
print(sol3.members.loc['ecoli1', 'growth_rate'].round(6) == sol3.members.loc['ecoli2', 'growth_rate'].round(6))
```
Expected output:
```
True
True
True
```
Obtained output:
```
False
True
True
```
Is the reasoning correct?
I was wondering if this behaviour has been observed before and if the solver version could make a difference, or else what could be done to avoid it.

Cheers,
Guido

**Comment by cdiener** [comment]
So there is two things going on and one is indeed related to bad numeric conditioning. Let's unpack it.

1. pFBA solutions are different

This one is not related to numerical accuracy, but rather the fact that pFBA solutions are not unique. You can see that easily with a simple thought example. Let's assume your biomass requires 1 unit of A at its maximal value and you have two reactions producing a unit of A for example `rxn1: X -> A` and `rxn2: Y -> A`. For pFBA you minimize the sum of absolute fluxes to reach max biomass, so an optimal solution fulfills `v_1 + v_2 = 1`. As you can see that can be reached with various solutions like `v_1 = 1, v_2 = 0`, `v_1 = 0, v_2 = 1`, or `v_1 = 0.5, v_2 = 0.5`. So pFBA makes the flux space smaller but not necessarily a single point. 

2. Growth rates are different

So in solution 1 you get different growth rates for the two taxa even though they should have the same growth rate (since that is actually the example from Fig. 1 in the paper). This one is related to numerical accuracies, however in that case it the optimality tolerance and not the feasible one. Both of your solutions are marked as optimal (you can check by `sol1.status`). However when you enable logging with 

```Python
from micom.logger import logger
logger.setLevel("INFO")
```

that all three optimizations give a warning that a numerically inaccurate solution was obtained. This is due to the quadratic optimization step. Interior point methods for QP problems tend to be less accurate and often can not get solutions in the required tolerance but a slightly relaxed tolerance (think 1e-5 instead of 1e-6). See #29 for a discussion. There is no way of improving on the optimality of the solution (better growth rate estimates), but you can improve the feasibility (try to get bound compliance back to 1e-6) and that is done with a crossover step in MICOM that solves an additional LP problem. Numerical accuracy can come from many places, in that case, the medium definitely has an impact since it enforces huge import fluxes. If you lower the imports to a maximum of 10 for each metabolite you get growth rates that are about 75% of the original values but their accuracy is now in the order of 1e-6 (the nominal feasibility tolerance). Also note that you comparison is not strictly what is tested. The actual feasibility criterion is `|v - v_opt|` < 1e-6 * |v_opt| + 1e-6`, so there is a relative and absolute tolerance and the guarantee is made in regard to the unknown "real" optimum. Sometimes running a few more iterations can improve accuracy (which is what you observe in solution 3) but this can also go the other way and break the solution basis.

Has it been observed before? Oh yes, and I would say about 1/4 of MICOM code is trying to improve numerical accuracy.

**What can you make of this?**

Large models with non-curated media compositions are often numerically unstable. A good rule of thumb is to assume everything is good up to a relative error of 10x the nominal tolerance (so 1e-5 by default). This may not sound great if you are coming from numerical mathematics but it is pretty good for biology. You will never measure a growth rate of flux up to an accuracy of 99.9999% in the lab. But one should definitely check that differences observed with MICOM have a realistic magnitude. If a flux fairly large and is suddenly 2x larger you are probably in the clear.
